require 'rubocop/cop/mavenlint/unsafe_mass_assignment'
require 'rubocop/cop/mavenlint/use_application_record'
require 'rubocop/cop/mavenlint/use_application_controller'
require 'rubocop/cop/mavenlint/use_api_controller'
require 'rubocop/cop/mavenlint/use_fast_capybara_matchers'
require 'rubocop/cop/mavenlint/direct_factory_bot_invocation'
require 'rubocop/cop/mavenlint/require_slow_helpers'
require 'rubocop/cop/mavenlint/bigint_for_migration_keys'
