require 'rubocop/cop/mavenlint/unsafe_mass_assignment'
require 'rubocop/cop/mavenlint/use_application_record'
require 'rubocop/cop/mavenlint/use_application_controller'
require 'rubocop/cop/mavenlint/use_api_controller'
require 'rubocop/cop/mavenlint/use_fast_capybara_matchers'
